export const FETCH_ALL_DECKS_SUCCESS = 'FETCH_ALL_DECKS_SUCCESS';
export const FETCH_ALL_DECKS_FAILURE = 'FETCH_ALL_DECKS_FAILURE';

export const ADD_DECK_SUCCESS = 'ADD_DECK_SUCCESS';
export const ADD_DECK_FAILURE = 'ADD_DECK_FAILURE';
