export const FETCH_ALL_DECKS_SUCCESS = 'FETCH_ALL_DECKS_SUCCESS';
export const FETCH_ALL_DECKS_FAILURE = 'FETCH_ALL_DECKS_FAILURE';

export const ADD_DECK_SUCCESS = 'ADD_DECK_SUCCESS';
export const ADD_DECK_FAILURE = 'ADD_DECK_FAILURE';

export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';

export const EDIT_DECK_SUCCESS = 'EDIT_DECK_SUCCESS';
export const EDIT_DECK_FAILURE = 'EDIT_DECK_FAILURE';

export const EDIT_CARD_SUCCESS = 'EDIT_CARD_SUCCESS';
export const EDIT_CARD_FAILURE = 'EDIT_CARD_FAILURE';
